2023-05-20 12:44:12,657 ERROR [ContactDao] Error cause by :
org.h2.jdbc.JdbcSQLIntegrityConstraintViolationException: Unique index or primary key violation: "PUBLIC.TELE1_UK_INDEX_6 ON PUBLIC.CONTACT(TELE1 NULLS FIRST) VALUES ( /* 15 */ '061206143311' )"; SQL statement:
insert into contact(nom,prenom,tele1,tele2,adresse,email_personnel,email_professionnel,genre)values(?,?,?,?,?,?,?,?) [23505-214]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:508)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:477)
	at org.h2.message.DbException.get(DbException.java:223)
	at org.h2.message.DbException.get(DbException.java:199)
	at org.h2.index.Index.getDuplicateKeyException(Index.java:525)
	at org.h2.mvstore.db.MVSecondaryIndex.checkUnique(MVSecondaryIndex.java:223)
	at org.h2.mvstore.db.MVSecondaryIndex.add(MVSecondaryIndex.java:184)
	at org.h2.mvstore.db.MVTable.addRow(MVTable.java:519)
	at org.h2.command.dml.Insert.insertRows(Insert.java:174)
	at org.h2.command.dml.Insert.update(Insert.java:135)
	at org.h2.command.dml.DataChangeStatement.update(DataChangeStatement.java:74)
	at org.h2.command.CommandContainer.update(CommandContainer.java:169)
	at org.h2.command.Command.executeUpdate(Command.java:252)
	at org.h2.jdbc.JdbcPreparedStatement.executeUpdateInternal(JdbcPreparedStatement.java:209)
	at org.h2.jdbc.JdbcPreparedStatement.executeUpdate(JdbcPreparedStatement.java:169)
	at g_contact.data.ContactDao.create(ContactDao.java:46)
	at g_contact.ihm.Main.main(Main.java:19)
2023-05-20 12:48:37,479 ERROR [ContactDao] Error cause by :
org.h2.jdbc.JdbcSQLIntegrityConstraintViolationException: Unique index or primary key violation: "PUBLIC.TELE1_UK_INDEX_6 ON PUBLIC.CONTACT(TELE1 NULLS FIRST) VALUES ( /* 15 */ '061206143311' )"; SQL statement:
insert into contact(nom,prenom,tele1,tele2,adresse,email_personnel,email_professionnel,genre)values(?,?,?,?,?,?,?,?) [23505-214]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:508)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:477)
	at org.h2.message.DbException.get(DbException.java:223)
	at org.h2.message.DbException.get(DbException.java:199)
	at org.h2.index.Index.getDuplicateKeyException(Index.java:525)
	at org.h2.mvstore.db.MVSecondaryIndex.checkUnique(MVSecondaryIndex.java:223)
	at org.h2.mvstore.db.MVSecondaryIndex.add(MVSecondaryIndex.java:184)
	at org.h2.mvstore.db.MVTable.addRow(MVTable.java:519)
	at org.h2.command.dml.Insert.insertRows(Insert.java:174)
	at org.h2.command.dml.Insert.update(Insert.java:135)
	at org.h2.command.dml.DataChangeStatement.update(DataChangeStatement.java:74)
	at org.h2.command.CommandContainer.update(CommandContainer.java:169)
	at org.h2.command.Command.executeUpdate(Command.java:252)
	at org.h2.jdbc.JdbcPreparedStatement.executeUpdateInternal(JdbcPreparedStatement.java:209)
	at org.h2.jdbc.JdbcPreparedStatement.executeUpdate(JdbcPreparedStatement.java:169)
	at g_contact.data.ContactDao.create(ContactDao.java:46)
	at g_contact.bll.ContactManager.addContact(ContactManager.java:28)
	at g_contact.ihm.Main.main(Main.java:22)
2023-05-20 12:53:43,458 ERROR [ContactDao] Error cause by :
org.h2.jdbc.JdbcSQLIntegrityConstraintViolationException: Unique index or primary key violation: "PUBLIC.TELE1_UK_INDEX_6 ON PUBLIC.CONTACT(TELE1 NULLS FIRST) VALUES ( /* 15 */ '061206143311' )"; SQL statement:
insert into contact(nom,prenom,tele1,tele2,adresse,email_personnel,email_professionnel,genre)values(?,?,?,?,?,?,?,?) [23505-214]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:508)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:477)
	at org.h2.message.DbException.get(DbException.java:223)
	at org.h2.message.DbException.get(DbException.java:199)
	at org.h2.index.Index.getDuplicateKeyException(Index.java:525)
	at org.h2.mvstore.db.MVSecondaryIndex.checkUnique(MVSecondaryIndex.java:223)
	at org.h2.mvstore.db.MVSecondaryIndex.add(MVSecondaryIndex.java:184)
	at org.h2.mvstore.db.MVTable.addRow(MVTable.java:519)
	at org.h2.command.dml.Insert.insertRows(Insert.java:174)
	at org.h2.command.dml.Insert.update(Insert.java:135)
	at org.h2.command.dml.DataChangeStatement.update(DataChangeStatement.java:74)
	at org.h2.command.CommandContainer.update(CommandContainer.java:169)
	at org.h2.command.Command.executeUpdate(Command.java:252)
	at org.h2.jdbc.JdbcPreparedStatement.executeUpdateInternal(JdbcPreparedStatement.java:209)
	at org.h2.jdbc.JdbcPreparedStatement.executeUpdate(JdbcPreparedStatement.java:169)
	at g_contact.data.ContactDao.create(ContactDao.java:46)
	at g_contact.bll.ContactManager.addContact(ContactManager.java:28)
	at g_contact.ihm.Main.main(Main.java:22)
2023-05-20 12:58:56,360 ERROR [ContactDao] Error caused by :
org.h2.jdbc.JdbcSQLIntegrityConstraintViolationException: Unique index or primary key violation: "PUBLIC.TELE1_UK_INDEX_6 ON PUBLIC.CONTACT(TELE1 NULLS FIRST) VALUES ( /* 15 */ '061206143311' )"; SQL statement:
insert into contact(nom,prenom,tele1,tele2,adresse,email_personnel,email_professionnel,genre)values(?,?,?,?,?,?,?,?) [23505-214]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:508)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:477)
	at org.h2.message.DbException.get(DbException.java:223)
	at org.h2.message.DbException.get(DbException.java:199)
	at org.h2.index.Index.getDuplicateKeyException(Index.java:525)
	at org.h2.mvstore.db.MVSecondaryIndex.checkUnique(MVSecondaryIndex.java:223)
	at org.h2.mvstore.db.MVSecondaryIndex.add(MVSecondaryIndex.java:184)
	at org.h2.mvstore.db.MVTable.addRow(MVTable.java:519)
	at org.h2.command.dml.Insert.insertRows(Insert.java:174)
	at org.h2.command.dml.Insert.update(Insert.java:135)
	at org.h2.command.dml.DataChangeStatement.update(DataChangeStatement.java:74)
	at org.h2.command.CommandContainer.update(CommandContainer.java:169)
	at org.h2.command.Command.executeUpdate(Command.java:252)
	at org.h2.jdbc.JdbcPreparedStatement.executeUpdateInternal(JdbcPreparedStatement.java:209)
	at org.h2.jdbc.JdbcPreparedStatement.executeUpdate(JdbcPreparedStatement.java:169)
	at g_contact.data.ContactDao.create(ContactDao.java:43)
	at g_contact.bll.ContactManager.addContact(ContactManager.java:28)
	at g_contact.ihm.Main.main(Main.java:22)
2023-05-20 13:03:20,659 ERROR [ContactDao] Error caused by :
org.h2.jdbc.JdbcSQLIntegrityConstraintViolationException: Unique index or primary key violation: "PUBLIC.TELE1_UK_INDEX_6 ON PUBLIC.CONTACT(TELE1 NULLS FIRST) VALUES ( /* 15 */ '061206143311' )"; SQL statement:
insert into contact(nom,prenom,tele1,tele2,adresse,email_personnel,email_professionnel,genre)values(?,?,?,?,?,?,?,?) [23505-214]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:508)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:477)
	at org.h2.message.DbException.get(DbException.java:223)
	at org.h2.message.DbException.get(DbException.java:199)
	at org.h2.index.Index.getDuplicateKeyException(Index.java:525)
	at org.h2.mvstore.db.MVSecondaryIndex.checkUnique(MVSecondaryIndex.java:223)
	at org.h2.mvstore.db.MVSecondaryIndex.add(MVSecondaryIndex.java:184)
	at org.h2.mvstore.db.MVTable.addRow(MVTable.java:519)
	at org.h2.command.dml.Insert.insertRows(Insert.java:174)
	at org.h2.command.dml.Insert.update(Insert.java:135)
	at org.h2.command.dml.DataChangeStatement.update(DataChangeStatement.java:74)
	at org.h2.command.CommandContainer.update(CommandContainer.java:169)
	at org.h2.command.Command.executeUpdate(Command.java:252)
	at org.h2.jdbc.JdbcPreparedStatement.executeUpdateInternal(JdbcPreparedStatement.java:209)
	at org.h2.jdbc.JdbcPreparedStatement.executeUpdate(JdbcPreparedStatement.java:169)
	at g_contact.data.ContactDao.create(ContactDao.java:43)
	at g_contact.bll.ContactManager.addContact(ContactManager.java:28)
	at g_contact.ihm.Main.main(Main.java:21)
2023-05-20 13:15:10,880 ERROR [ContactDao] Error caused by :
org.h2.jdbc.JdbcSQLSyntaxErrorException: Syntax error in SQL statement "SELECT * FROM Contact WHERE nom = ? and upper [*]prenom = ?"; SQL statement:
SELECT * FROM Contact WHERE nom = ? and upper prenom = ? [42000-214]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:502)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:477)
	at org.h2.message.DbException.get(DbException.java:223)
	at org.h2.message.DbException.get(DbException.java:199)
	at org.h2.message.DbException.getSyntaxError(DbException.java:247)
	at org.h2.command.Parser.getSyntaxError(Parser.java:898)
	at org.h2.command.Parser.prepareCommand(Parser.java:572)
	at org.h2.engine.SessionLocal.prepareLocal(SessionLocal.java:631)
	at org.h2.engine.SessionLocal.prepareCommand(SessionLocal.java:554)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1116)
	at org.h2.jdbc.JdbcPreparedStatement.<init>(JdbcPreparedStatement.java:92)
	at org.h2.jdbc.JdbcConnection.prepareStatement(JdbcConnection.java:288)
	at g_contact.data.ContactDao.findContactByName(ContactDao.java:131)
	at g_contact.bll.ContactManager.addContact(ContactManager.java:22)
	at g_contact.ihm.Main.main(Main.java:21)
2023-05-20 16:31:34,584 ERROR [DbConnection] org.h2.jdbc.JdbcSQLNonTransientConnectionException: Database may be already in use: "C:/Users/dell/h2_Db/bibDb4.mv.db". Possible solutions: close all other connection(s); use the server mode [90020-214]
2023-05-20 18:41:14,426 ERROR [DbConnection] org.h2.jdbc.JdbcSQLNonTransientConnectionException: Database may be already in use: "C:/Users/dell/h2_Db/bibDb4.mv.db". Possible solutions: close all other connection(s); use the server mode [90020-214]
2023-05-20 18:41:40,020 ERROR [DbConnection] org.h2.jdbc.JdbcSQLNonTransientConnectionException: Database may be already in use: "C:/Users/dell/h2_Db/bibDb4.mv.db". Possible solutions: close all other connection(s); use the server mode [90020-214]
2023-05-20 18:41:50,011 ERROR [DbConnection] org.h2.jdbc.JdbcSQLNonTransientConnectionException: Database may be already in use: "C:/Users/dell/h2_Db/bibDb4.mv.db". Possible solutions: close all other connection(s); use the server mode [90020-214]
2023-05-20 18:41:58,712 ERROR [DbConnection] org.h2.jdbc.JdbcSQLNonTransientConnectionException: Database may be already in use: "C:/Users/dell/h2_Db/bibDb4.mv.db". Possible solutions: close all other connection(s); use the server mode [90020-214]
2023-05-20 18:42:32,271 ERROR [DbConnection] org.h2.jdbc.JdbcSQLNonTransientConnectionException: Database may be already in use: "C:/Users/dell/h2_Db/bibDb4.mv.db". Possible solutions: close all other connection(s); use the server mode [90020-214]
2023-05-20 18:43:26,643 ERROR [DbConnection] org.h2.jdbc.JdbcSQLNonTransientConnectionException: Database may be already in use: "C:/Users/dell/h2_Db/bibDb4.mv.db". Possible solutions: close all other connection(s); use the server mode [90020-214]
2023-05-20 18:46:29,896 ERROR [DbConnection] org.h2.jdbc.JdbcSQLNonTransientConnectionException: Database may be already in use: "C:/Users/dell/h2_Db/bibDb4.mv.db". Possible solutions: close all other connection(s); use the server mode [90020-214]
2023-05-20 20:23:12,448 ERROR [ContactDao] Error caused by: 
org.h2.jdbc.JdbcSQLSyntaxErrorException: Column "EMAIL_PROFESSIONEL" not found; SQL statement:
UPDATE CONTACT SET nom=?,prenom=?,tele1=?,tele2=?,Adresse=?,email_personnel=?,email_professionel=?,genre=? WHERE id =? [42122-214]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:502)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:477)
	at org.h2.message.DbException.get(DbException.java:223)
	at org.h2.message.DbException.get(DbException.java:199)
	at org.h2.table.Table.getColumn(Table.java:749)
	at org.h2.command.Parser.readTableColumn(Parser.java:1084)
	at org.h2.command.Parser.readUpdateSetClause(Parser.java:1151)
	at org.h2.command.Parser.parseUpdate(Parser.java:1120)
	at org.h2.command.Parser.parsePrepared(Parser.java:858)
	at org.h2.command.Parser.parse(Parser.java:689)
	at org.h2.command.Parser.parse(Parser.java:661)
	at org.h2.command.Parser.prepareCommand(Parser.java:569)
	at org.h2.engine.SessionLocal.prepareLocal(SessionLocal.java:631)
	at org.h2.engine.SessionLocal.prepareCommand(SessionLocal.java:554)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1116)
	at org.h2.jdbc.JdbcPreparedStatement.<init>(JdbcPreparedStatement.java:92)
	at org.h2.jdbc.JdbcConnection.prepareStatement(JdbcConnection.java:288)
	at g_contact.data.ContactDao.update(ContactDao.java:107)
	at g_contact.bll.ContactManager.update(ContactManager.java:66)
	at g_contact.ihm.Main.main(Main.java:147)
2023-05-20 21:22:07,356 ERROR [ContactDao] Error caused by: 
org.h2.jdbc.JdbcSQLSyntaxErrorException: Column "EMAIL_PROFESSIONEL" not found; SQL statement:
UPDATE CONTACT SET nom=?,prenom=?,tele1=?,tele2=?,Adresse=?,email_personnel=?,email_professionel=?,genre=? WHERE nom =? and prenom =? [42122-214]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:502)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:477)
	at org.h2.message.DbException.get(DbException.java:223)
	at org.h2.message.DbException.get(DbException.java:199)
	at org.h2.table.Table.getColumn(Table.java:749)
	at org.h2.command.Parser.readTableColumn(Parser.java:1084)
	at org.h2.command.Parser.readUpdateSetClause(Parser.java:1151)
	at org.h2.command.Parser.parseUpdate(Parser.java:1120)
	at org.h2.command.Parser.parsePrepared(Parser.java:858)
	at org.h2.command.Parser.parse(Parser.java:689)
	at org.h2.command.Parser.parse(Parser.java:661)
	at org.h2.command.Parser.prepareCommand(Parser.java:569)
	at org.h2.engine.SessionLocal.prepareLocal(SessionLocal.java:631)
	at org.h2.engine.SessionLocal.prepareCommand(SessionLocal.java:554)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1116)
	at org.h2.jdbc.JdbcPreparedStatement.<init>(JdbcPreparedStatement.java:92)
	at org.h2.jdbc.JdbcConnection.prepareStatement(JdbcConnection.java:288)
	at g_contact.data.ContactDao.update(ContactDao.java:107)
	at g_contact.bll.ContactManager.update(ContactManager.java:66)
	at g_contact.ihm.Main.main(Main.java:134)
2023-05-20 21:45:13,477 ERROR [ContactDao] Error caused by: 
org.h2.jdbc.JdbcSQLSyntaxErrorException: Column "EMAIL_PROFESSIONEL" not found; SQL statement:
UPDATE CONTACT SET nom=?,prenom=?,tele1=?,tele2=?,Adresse=?,email_personnel=?,email_professionel=?,genre=? WHERE nom =? or prenom =? or tele1=? or tele2=? or Adresse=? or email_personnel=? or email_professionel=? or genre=? [42122-214]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:502)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:477)
	at org.h2.message.DbException.get(DbException.java:223)
	at org.h2.message.DbException.get(DbException.java:199)
	at org.h2.table.Table.getColumn(Table.java:749)
	at org.h2.command.Parser.readTableColumn(Parser.java:1084)
	at org.h2.command.Parser.readUpdateSetClause(Parser.java:1151)
	at org.h2.command.Parser.parseUpdate(Parser.java:1120)
	at org.h2.command.Parser.parsePrepared(Parser.java:858)
	at org.h2.command.Parser.parse(Parser.java:689)
	at org.h2.command.Parser.parse(Parser.java:661)
	at org.h2.command.Parser.prepareCommand(Parser.java:569)
	at org.h2.engine.SessionLocal.prepareLocal(SessionLocal.java:631)
	at org.h2.engine.SessionLocal.prepareCommand(SessionLocal.java:554)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1116)
	at org.h2.jdbc.JdbcPreparedStatement.<init>(JdbcPreparedStatement.java:92)
	at org.h2.jdbc.JdbcConnection.prepareStatement(JdbcConnection.java:288)
	at g_contact.data.ContactDao.update(ContactDao.java:106)
	at g_contact.bll.ContactManager.update(ContactManager.java:66)
	at g_contact.ihm.Main.main(Main.java:134)
2023-05-20 22:00:49,520 ERROR [DbConnection] org.h2.jdbc.JdbcSQLNonTransientConnectionException: Database may be already in use: "C:/Users/dell/h2_Db/bibDb4.mv.db". Possible solutions: close all other connection(s); use the server mode [90020-214]
2023-05-20 22:01:35,278 ERROR [ContactDao] Error caused by: 
org.h2.jdbc.JdbcSQLSyntaxErrorException: Column "EMAIL_PROFESSIONEL" not found; SQL statement:
UPDATE CONTACT SET nom=?,prenom='?',tele1='?',tele2='?',adresse='?',email_personnel='?',email_professionel='?',genre='?' WHERE nom ='?' or prenom ='?' or tele1='?' or tele2='?' or adresse='?' or email_personnel='?' or email_professionel='?' or genre='?' [42122-214]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:502)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:477)
	at org.h2.message.DbException.get(DbException.java:223)
	at org.h2.message.DbException.get(DbException.java:199)
	at org.h2.table.Table.getColumn(Table.java:749)
	at org.h2.command.Parser.readTableColumn(Parser.java:1084)
	at org.h2.command.Parser.readUpdateSetClause(Parser.java:1151)
	at org.h2.command.Parser.parseUpdate(Parser.java:1120)
	at org.h2.command.Parser.parsePrepared(Parser.java:858)
	at org.h2.command.Parser.parse(Parser.java:689)
	at org.h2.command.Parser.parse(Parser.java:661)
	at org.h2.command.Parser.prepareCommand(Parser.java:569)
	at org.h2.engine.SessionLocal.prepareLocal(SessionLocal.java:631)
	at org.h2.engine.SessionLocal.prepareCommand(SessionLocal.java:554)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1116)
	at org.h2.jdbc.JdbcPreparedStatement.<init>(JdbcPreparedStatement.java:92)
	at org.h2.jdbc.JdbcConnection.prepareStatement(JdbcConnection.java:288)
	at g_contact.data.ContactDao.update(ContactDao.java:107)
	at g_contact.bll.ContactManager.update(ContactManager.java:66)
	at g_contact.ihm.Main.main(Main.java:134)
2023-05-21 10:35:25,126 ERROR [ContactDao] Error caused by: 
org.h2.jdbc.JdbcSQLSyntaxErrorException: Column "EMAIL_PROFESSIONEL" not found; SQL statement:
UPDATE CONTACT SET nom=?,prenom='?',tele1='?',tele2='?',adresse='?',email_personnel='?',Email_professionnel='?',genre='?' WHERE nom ='?' or prenom ='?' or tele1='?' or tele2='?' or adresse='?' or email_personnel='?' or email_professionel='?' or genre='?' [42122-214]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:502)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:477)
	at org.h2.message.DbException.get(DbException.java:223)
	at org.h2.message.DbException.get(DbException.java:199)
	at org.h2.expression.ExpressionColumn.getColumnException(ExpressionColumn.java:244)
	at org.h2.expression.ExpressionColumn.optimizeOther(ExpressionColumn.java:226)
	at org.h2.expression.ExpressionColumn.optimize(ExpressionColumn.java:213)
	at org.h2.expression.condition.Comparison.optimize(Comparison.java:139)
	at org.h2.expression.condition.ConditionAndOrN.optimize(ConditionAndOrN.java:168)
	at org.h2.expression.Expression.optimizeCondition(Expression.java:148)
	at org.h2.command.dml.Update.doPrepare(Update.java:143)
	at org.h2.command.dml.DataChangeStatement.prepare(DataChangeStatement.java:37)
	at org.h2.command.Parser.prepareCommand(Parser.java:575)
	at org.h2.engine.SessionLocal.prepareLocal(SessionLocal.java:631)
	at org.h2.engine.SessionLocal.prepareCommand(SessionLocal.java:554)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1116)
	at org.h2.jdbc.JdbcPreparedStatement.<init>(JdbcPreparedStatement.java:92)
	at org.h2.jdbc.JdbcConnection.prepareStatement(JdbcConnection.java:288)
	at g_contact.data.ContactDao.update(ContactDao.java:107)
	at g_contact.bll.ContactManager.update(ContactManager.java:66)
	at g_contact.ihm.Main.main(Main.java:134)
2023-05-21 10:36:52,416 ERROR [DbConnection] org.h2.jdbc.JdbcSQLNonTransientConnectionException: Database may be already in use: "C:/Users/dell/h2_Db/bibDb4.mv.db". Possible solutions: close all other connection(s); use the server mode [90020-214]
2023-05-21 10:38:31,612 ERROR [ContactDao] Error caused by: 
org.h2.jdbc.JdbcSQLSyntaxErrorException: Column "EMAIL_PROFESSIONEL" not found; SQL statement:
UPDATE CONTACT SET nom=?,prenom='?',tele1='?',tele2='?',adresse='?',email_personnel='?',Email_professionnel='?',genre='?' WHERE nom ='?' or prenom ='?' or tele1='?' or tele2='?' or adresse='?' or email_personnel='?' or email_professionel='?' or genre='?' [42122-214]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:502)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:477)
	at org.h2.message.DbException.get(DbException.java:223)
	at org.h2.message.DbException.get(DbException.java:199)
	at org.h2.expression.ExpressionColumn.getColumnException(ExpressionColumn.java:244)
	at org.h2.expression.ExpressionColumn.optimizeOther(ExpressionColumn.java:226)
	at org.h2.expression.ExpressionColumn.optimize(ExpressionColumn.java:213)
	at org.h2.expression.condition.Comparison.optimize(Comparison.java:139)
	at org.h2.expression.condition.ConditionAndOrN.optimize(ConditionAndOrN.java:168)
	at org.h2.expression.Expression.optimizeCondition(Expression.java:148)
	at org.h2.command.dml.Update.doPrepare(Update.java:143)
	at org.h2.command.dml.DataChangeStatement.prepare(DataChangeStatement.java:37)
	at org.h2.command.Parser.prepareCommand(Parser.java:575)
	at org.h2.engine.SessionLocal.prepareLocal(SessionLocal.java:631)
	at org.h2.engine.SessionLocal.prepareCommand(SessionLocal.java:554)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1116)
	at org.h2.jdbc.JdbcPreparedStatement.<init>(JdbcPreparedStatement.java:92)
	at org.h2.jdbc.JdbcConnection.prepareStatement(JdbcConnection.java:288)
	at g_contact.data.ContactDao.update(ContactDao.java:107)
	at g_contact.bll.ContactManager.update(ContactManager.java:66)
	at g_contact.ihm.Main.main(Main.java:134)
2023-05-21 10:39:57,187 ERROR [ContactDao] Error caused by: 
org.h2.jdbc.JdbcSQLDataException: Invalid value "2" for parameter "parameterIndex" [90008-214]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:646)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:477)
	at org.h2.message.DbException.get(DbException.java:223)
	at org.h2.message.DbException.getInvalidValueException(DbException.java:298)
	at org.h2.jdbc.JdbcPreparedStatement.setParameter(JdbcPreparedStatement.java:1395)
	at org.h2.jdbc.JdbcPreparedStatement.setString(JdbcPreparedStatement.java:378)
	at g_contact.data.ContactDao.update(ContactDao.java:109)
	at g_contact.bll.ContactManager.update(ContactManager.java:66)
	at g_contact.ihm.Main.main(Main.java:134)
2023-05-21 10:47:13,064 ERROR [ContactDao] Error caused by: 
org.h2.jdbc.JdbcSQLDataException: Invalid value "10" for parameter "parameterIndex" [90008-214]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:646)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:477)
	at org.h2.message.DbException.get(DbException.java:223)
	at org.h2.message.DbException.getInvalidValueException(DbException.java:298)
	at org.h2.jdbc.JdbcPreparedStatement.setParameter(JdbcPreparedStatement.java:1395)
	at org.h2.jdbc.JdbcPreparedStatement.setString(JdbcPreparedStatement.java:378)
	at g_contact.data.ContactDao.update(ContactDao.java:117)
	at g_contact.bll.ContactManager.update(ContactManager.java:66)
	at g_contact.ihm.Main.main(Main.java:134)
2023-05-21 10:49:07,249 ERROR [ContactDao] Error caused by: 
org.h2.jdbc.JdbcSQLDataException: Invalid value "10" for parameter "parameterIndex" [90008-214]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:646)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:477)
	at org.h2.message.DbException.get(DbException.java:223)
	at org.h2.message.DbException.getInvalidValueException(DbException.java:298)
	at org.h2.jdbc.JdbcPreparedStatement.setParameter(JdbcPreparedStatement.java:1395)
	at org.h2.jdbc.JdbcPreparedStatement.setString(JdbcPreparedStatement.java:378)
	at g_contact.data.ContactDao.update(ContactDao.java:117)
	at g_contact.bll.ContactManager.update(ContactManager.java:66)
	at g_contact.ihm.Main.main(Main.java:134)
2023-05-26 19:27:05,215 ERROR [ContactDao] Error caused by :
org.h2.jdbc.JdbcSQLIntegrityConstraintViolationException: Unique index or primary key violation: "PUBLIC.EMAIL_PROFESSIONNEL_UK_INDEX_6 ON PUBLIC.CONTACT(EMAIL_PROFESSIONNEL NULLS FIRST) VALUES ( /* 24 */ 'asdf' )"; SQL statement:
insert into contact(nom,prenom,tele1,tele2,adresse,email_personnel,email_professionnel,genre)values(?,?,?,?,?,?,?,?) [23505-214]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:508)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:477)
	at org.h2.message.DbException.get(DbException.java:223)
	at org.h2.message.DbException.get(DbException.java:199)
	at org.h2.index.Index.getDuplicateKeyException(Index.java:525)
	at org.h2.mvstore.db.MVSecondaryIndex.checkUnique(MVSecondaryIndex.java:223)
	at org.h2.mvstore.db.MVSecondaryIndex.add(MVSecondaryIndex.java:184)
	at org.h2.mvstore.db.MVTable.addRow(MVTable.java:519)
	at org.h2.command.dml.Insert.insertRows(Insert.java:174)
	at org.h2.command.dml.Insert.update(Insert.java:135)
	at org.h2.command.dml.DataChangeStatement.update(DataChangeStatement.java:74)
	at org.h2.command.CommandContainer.update(CommandContainer.java:169)
	at org.h2.command.Command.executeUpdate(Command.java:252)
	at org.h2.jdbc.JdbcPreparedStatement.executeUpdateInternal(JdbcPreparedStatement.java:209)
	at org.h2.jdbc.JdbcPreparedStatement.executeUpdate(JdbcPreparedStatement.java:169)
	at g_contact.data.ContactDao.create(ContactDao.java:45)
	at g_contact.bll.ContactManager.addContact(ContactManager.java:28)
	at g_contact.ihm.Main.main(Main.java:74)
2023-05-26 21:54:41,660 ERROR [Main] Syntax error in SQL statement "CREATE TABLE [*]group(\000aid_group bigint auto_increment,\000agroup_name VARCHAR(255),\000aPRIMARY KEY (id_group)\000a);\000a\000aCREATE TABLE GroupContact(\000aid bigint,\000aid_group bigint,\000aCONSTRAINT FOREIGN KEY (id) REFERENCES contact(id),\000aCONSTRAINT FOREIGN KEY (id_group) REFERENCES group(id_group),\000a);\000a"; expected "identifier"; SQL statement:
CREATE TABLE group(
id_group bigint auto_increment,
group_name VARCHAR(255),
PRIMARY KEY (id_group)
);

CREATE TABLE GroupContact(
id bigint,
id_group bigint,
CONSTRAINT FOREIGN KEY (id) REFERENCES contact(id),
CONSTRAINT FOREIGN KEY (id_group) REFERENCES group(id_group),
);
 [42001-214]
2023-05-26 21:56:51,670 ERROR [DbConnection] org.h2.jdbc.JdbcSQLNonTransientConnectionException: Database may be already in use: "C:/Users/dell/h2_Db/bibDb4.mv.db". Possible solutions: close all other connection(s); use the server mode [90020-214]
2023-05-26 21:57:13,220 ERROR [Main] Syntax error in SQL statement "CREATE TABLE [*]group(\000aid_group bigint auto_increment,\000agroup_name VARCHAR(255),\000aPRIMARY KEY (id_group)\000a);\000a\000aCREATE TABLE GroupContact(\000aid bigint,\000aid_group bigint,\000aFOREIGN KEY (id) REFERENCES contact(id),\000aFOREIGN KEY (id_group) REFERENCES group(id_group),\000a);\000a"; expected "identifier"; SQL statement:
CREATE TABLE group(
id_group bigint auto_increment,
group_name VARCHAR(255),
PRIMARY KEY (id_group)
);

CREATE TABLE GroupContact(
id bigint,
id_group bigint,
FOREIGN KEY (id) REFERENCES contact(id),
FOREIGN KEY (id_group) REFERENCES group(id_group),
);
 [42001-214]
2023-05-29 19:33:36,238 ERROR [Main] Syntax error in SQL statement "CREATE TABLE [*]group(\000agroup_name VARCHAR(255),\000acontact_id bigint\000a);\000a"; expected "identifier"; SQL statement:
CREATE TABLE group(
group_name VARCHAR(255),
contact_id bigint
);
 [42001-214]
2023-05-29 19:36:02,804 ERROR [Main] Syntax error in SQL statement "CREATE TABLE [*]group(\000agroup_name VARCHAR(255),\000acontact_id bigint(100)\000a);\000a"; expected "identifier"; SQL statement:
CREATE TABLE group(
group_name VARCHAR(255),
contact_id bigint(100)
);
 [42001-214]
2023-05-29 19:37:32,007 ERROR [Main] Syntax error in SQL statement "CREATE TABLE [*]group(\000aid_group bigint,\000agroup_name VARCHAR(255),\000acontact_id bigint(100)\000aPRIMARY KEY (id_contact)\000a);\000a"; expected "identifier"; SQL statement:
CREATE TABLE group(
id_group bigint,
group_name VARCHAR(255),
contact_id bigint(100)
PRIMARY KEY (id_contact)
);
 [42001-214]
2023-05-29 19:39:42,653 ERROR [Main] Syntax error in SQL statement "CREATE TABLE `group`(\000agroup_name VARCHAR(255),\000acontact_id bigint[*](100)\000a);\000a"; expected "ARRAY, INVISIBLE, VISIBLE, NOT NULL, NULL, AS, DEFAULT, GENERATED, ON UPDATE, NOT NULL, NULL, AUTO_INCREMENT, DEFAULT ON NULL, NULL_TO_DEFAULT, SEQUENCE, SELECTIVITY, COMMENT, CONSTRAINT, COMMENT, PRIMARY KEY, UNIQUE, NOT NULL, NULL, CHECK, REFERENCES, AUTO_INCREMENT, ,, )"; SQL statement:
CREATE TABLE `group`(
group_name VARCHAR(255),
contact_id bigint(100)
);
 [42001-214]
2023-05-29 19:41:14,811  INFO [Main] Database created correctly
2023-05-29 19:46:42,541 ERROR [GroupDao] Syntax error in SQL statement "SELECT * FROM [*]group WHERE contact_id=?"; expected "identifier"; SQL statement:
SELECT * FROM group WHERE contact_id=? [42001-214]
2023-05-29 19:57:56,653 ERROR [GroupDao] Syntax error in SQL statement "SELECT * FROM [*]group WHERE contact_id=?"; expected "identifier"; SQL statement:
SELECT * FROM group WHERE contact_id=? [42001-214]
2023-05-29 20:01:04,378 ERROR [DbConnection] org.h2.jdbc.JdbcSQLNonTransientConnectionException: Database may be already in use: "C:/Users/dell/h2_Db/bibDb4.mv.db". Possible solutions: close all other connection(s); use the server mode [90020-214]
2023-05-29 20:01:57,377 ERROR [GroupDao] Syntax error in SQL statement "SELECT * FROM [*]group WHERE contact_id=?"; expected "identifier"; SQL statement:
SELECT * FROM group WHERE contact_id=? [42001-214]
2023-05-29 22:53:37,525 ERROR [GroupDao] Error caused by :
org.h2.jdbc.JdbcSQLSyntaxErrorException: Column "GROUP_NAME" not found; SQL statement:
insert into contact(group_name,contact_id)values(?,?) [42122-214]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:502)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:477)
	at org.h2.message.DbException.get(DbException.java:223)
	at org.h2.message.DbException.get(DbException.java:199)
	at org.h2.table.Table.getColumn(Table.java:749)
	at org.h2.command.Parser.parseColumn(Parser.java:1256)
	at org.h2.command.Parser.parseColumnList(Parser.java:1241)
	at org.h2.command.Parser.parseInsert(Parser.java:1641)
	at org.h2.command.Parser.parsePrepared(Parser.java:814)
	at org.h2.command.Parser.parse(Parser.java:689)
	at org.h2.command.Parser.parse(Parser.java:661)
	at org.h2.command.Parser.prepareCommand(Parser.java:569)
	at org.h2.engine.SessionLocal.prepareLocal(SessionLocal.java:631)
	at org.h2.engine.SessionLocal.prepareCommand(SessionLocal.java:554)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1116)
	at org.h2.jdbc.JdbcPreparedStatement.<init>(JdbcPreparedStatement.java:92)
	at org.h2.jdbc.JdbcConnection.prepareStatement(JdbcConnection.java:288)
	at g_contact.data.GroupDao.creatGroup(GroupDao.java:52)
	at g_contact.bll.GroupManager.addGroup(GroupManager.java:20)
	at g_contact.ihm.Main.main(Main.java:209)
2023-05-29 22:54:08,138 ERROR [GroupDao] Error caused by :
org.h2.jdbc.JdbcSQLSyntaxErrorException: Column "GROUP_NAME" not found; SQL statement:
insert into contact(group_name,contact_id)values(?,?) [42122-214]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:502)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:477)
	at org.h2.message.DbException.get(DbException.java:223)
	at org.h2.message.DbException.get(DbException.java:199)
	at org.h2.table.Table.getColumn(Table.java:749)
	at org.h2.command.Parser.parseColumn(Parser.java:1256)
	at org.h2.command.Parser.parseColumnList(Parser.java:1241)
	at org.h2.command.Parser.parseInsert(Parser.java:1641)
	at org.h2.command.Parser.parsePrepared(Parser.java:814)
	at org.h2.command.Parser.parse(Parser.java:689)
	at org.h2.command.Parser.parse(Parser.java:661)
	at org.h2.command.Parser.prepareCommand(Parser.java:569)
	at org.h2.engine.SessionLocal.prepareLocal(SessionLocal.java:631)
	at org.h2.engine.SessionLocal.prepareCommand(SessionLocal.java:554)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1116)
	at org.h2.jdbc.JdbcPreparedStatement.<init>(JdbcPreparedStatement.java:92)
	at org.h2.jdbc.JdbcConnection.prepareStatement(JdbcConnection.java:288)
	at g_contact.data.GroupDao.creatGroup(GroupDao.java:52)
	at g_contact.bll.GroupManager.addGroup(GroupManager.java:20)
	at g_contact.ihm.Main.main(Main.java:209)
2023-05-29 23:04:24,174 ERROR [DbConnection] org.h2.jdbc.JdbcSQLNonTransientConnectionException: Database may be already in use: "C:/Users/dell/h2_Db/bibDb4.mv.db". Possible solutions: close all other connection(s); use the server mode [90020-214]
2023-05-29 23:04:55,117 ERROR [GroupDao] Error caused by :
org.h2.jdbc.JdbcSQLSyntaxErrorException: Column "GROUP_NAME" not found; SQL statement:
insert into contact(group_name,contact_id)values(?,?) [42122-214]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:502)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:477)
	at org.h2.message.DbException.get(DbException.java:223)
	at org.h2.message.DbException.get(DbException.java:199)
	at org.h2.table.Table.getColumn(Table.java:749)
	at org.h2.command.Parser.parseColumn(Parser.java:1256)
	at org.h2.command.Parser.parseColumnList(Parser.java:1241)
	at org.h2.command.Parser.parseInsert(Parser.java:1641)
	at org.h2.command.Parser.parsePrepared(Parser.java:814)
	at org.h2.command.Parser.parse(Parser.java:689)
	at org.h2.command.Parser.parse(Parser.java:661)
	at org.h2.command.Parser.prepareCommand(Parser.java:569)
	at org.h2.engine.SessionLocal.prepareLocal(SessionLocal.java:631)
	at org.h2.engine.SessionLocal.prepareCommand(SessionLocal.java:554)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1116)
	at org.h2.jdbc.JdbcPreparedStatement.<init>(JdbcPreparedStatement.java:92)
	at org.h2.jdbc.JdbcConnection.prepareStatement(JdbcConnection.java:288)
	at g_contact.data.GroupDao.creatGroup(GroupDao.java:50)
	at g_contact.bll.GroupManager.addGroup(GroupManager.java:20)
	at g_contact.ihm.Main.main(Main.java:209)
2023-05-29 23:11:54,583  INFO [Main] Database created correctly
2023-05-29 23:13:23,434 ERROR [GroupDao] Error caused by :
org.h2.jdbc.JdbcSQLSyntaxErrorException: Column "GROUP_NAME" not found; SQL statement:
insert into contact(group_name,contact_id)values(?,?) [42122-214]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:502)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:477)
	at org.h2.message.DbException.get(DbException.java:223)
	at org.h2.message.DbException.get(DbException.java:199)
	at org.h2.table.Table.getColumn(Table.java:749)
	at org.h2.command.Parser.parseColumn(Parser.java:1256)
	at org.h2.command.Parser.parseColumnList(Parser.java:1241)
	at org.h2.command.Parser.parseInsert(Parser.java:1641)
	at org.h2.command.Parser.parsePrepared(Parser.java:814)
	at org.h2.command.Parser.parse(Parser.java:689)
	at org.h2.command.Parser.parse(Parser.java:661)
	at org.h2.command.Parser.prepareCommand(Parser.java:569)
	at org.h2.engine.SessionLocal.prepareLocal(SessionLocal.java:631)
	at org.h2.engine.SessionLocal.prepareCommand(SessionLocal.java:554)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1116)
	at org.h2.jdbc.JdbcPreparedStatement.<init>(JdbcPreparedStatement.java:92)
	at org.h2.jdbc.JdbcConnection.prepareStatement(JdbcConnection.java:288)
	at g_contact.data.GroupDao.creatGroup(GroupDao.java:50)
	at g_contact.bll.GroupManager.addGroup(GroupManager.java:20)
	at g_contact.ihm.Main.main(Main.java:209)
2023-05-29 23:17:13,283 ERROR [GroupDao] Error caused by :
org.h2.jdbc.JdbcSQLSyntaxErrorException: Table "CONTACTVALUES" not found; SQL statement:
insert into contactvalues(?,?) [42102-214]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:502)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:477)
	at org.h2.message.DbException.get(DbException.java:223)
	at org.h2.message.DbException.get(DbException.java:199)
	at org.h2.command.Parser.getTableOrViewNotFoundDbException(Parser.java:8398)
	at org.h2.command.Parser.getTableOrViewNotFoundDbException(Parser.java:8369)
	at org.h2.command.Parser.readTableOrView(Parser.java:8358)
	at org.h2.command.Parser.readTableOrView(Parser.java:8328)
	at org.h2.command.Parser.parseInsert(Parser.java:1632)
	at org.h2.command.Parser.parsePrepared(Parser.java:814)
	at org.h2.command.Parser.parse(Parser.java:689)
	at org.h2.command.Parser.parse(Parser.java:661)
	at org.h2.command.Parser.prepareCommand(Parser.java:569)
	at org.h2.engine.SessionLocal.prepareLocal(SessionLocal.java:631)
	at org.h2.engine.SessionLocal.prepareCommand(SessionLocal.java:554)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1116)
	at org.h2.jdbc.JdbcPreparedStatement.<init>(JdbcPreparedStatement.java:92)
	at org.h2.jdbc.JdbcConnection.prepareStatement(JdbcConnection.java:288)
	at g_contact.data.GroupDao.creatGroup(GroupDao.java:50)
	at g_contact.bll.GroupManager.addGroup(GroupManager.java:20)
	at g_contact.ihm.Main.main(Main.java:209)
2023-05-29 23:19:14,048 ERROR [GroupDao] Error caused by :
org.h2.jdbc.JdbcSQLSyntaxErrorException: Syntax error in SQL statement "insert into [*]group values(?,?)"; expected "identifier"; SQL statement:
insert into group values(?,?) [42001-214]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:502)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:477)
	at org.h2.message.DbException.getSyntaxError(DbException.java:261)
	at org.h2.command.Parser.readIdentifier(Parser.java:5656)
	at org.h2.command.Parser.readIdentifierWithSchema(Parser.java:5616)
	at org.h2.command.Parser.readTableOrView(Parser.java:8328)
	at org.h2.command.Parser.parseInsert(Parser.java:1632)
	at org.h2.command.Parser.parsePrepared(Parser.java:814)
	at org.h2.command.Parser.parse(Parser.java:689)
	at org.h2.command.Parser.parse(Parser.java:661)
	at org.h2.command.Parser.prepareCommand(Parser.java:569)
	at org.h2.engine.SessionLocal.prepareLocal(SessionLocal.java:631)
	at org.h2.engine.SessionLocal.prepareCommand(SessionLocal.java:554)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1116)
	at org.h2.jdbc.JdbcPreparedStatement.<init>(JdbcPreparedStatement.java:92)
	at org.h2.jdbc.JdbcConnection.prepareStatement(JdbcConnection.java:288)
	at g_contact.data.GroupDao.creatGroup(GroupDao.java:50)
	at g_contact.bll.GroupManager.addGroup(GroupManager.java:20)
	at g_contact.ihm.Main.main(Main.java:209)
2023-05-29 23:23:51,658 ERROR [DbConnection] org.h2.jdbc.JdbcSQLNonTransientConnectionException: Database may be already in use: "C:/Users/dell/h2_Db/bibDb4.mv.db". Possible solutions: close all other connection(s); use the server mode [90020-214]
2023-05-30 01:17:18,681 ERROR [GroupDao] Error caused by :
org.h2.jdbc.JdbcSQLSyntaxErrorException: Syntax error in SQL statement "SELECT group_name FROM [*]Group ORDER BY group_name"; expected "identifier"; SQL statement:
SELECT group_name FROM Group ORDER BY group_name [42001-214]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:502)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:477)
	at org.h2.message.DbException.getSyntaxError(DbException.java:261)
	at org.h2.command.Parser.readIdentifier(Parser.java:5656)
	at org.h2.command.Parser.readTablePrimary(Parser.java:1814)
	at org.h2.command.Parser.readTableReference(Parser.java:2334)
	at org.h2.command.Parser.parseSelectFromPart(Parser.java:2772)
	at org.h2.command.Parser.parseSelect(Parser.java:2878)
	at org.h2.command.Parser.parseQueryPrimary(Parser.java:2762)
	at org.h2.command.Parser.parseQueryTerm(Parser.java:2633)
	at org.h2.command.Parser.parseQueryExpressionBody(Parser.java:2612)
	at org.h2.command.Parser.parseQueryExpressionBodyAndEndOfQuery(Parser.java:2605)
	at org.h2.command.Parser.parseQueryExpression(Parser.java:2598)
	at org.h2.command.Parser.parseQuery(Parser.java:2567)
	at org.h2.command.Parser.parsePrepared(Parser.java:724)
	at org.h2.command.Parser.parse(Parser.java:689)
	at org.h2.command.Parser.parse(Parser.java:661)
	at org.h2.command.Parser.prepareCommand(Parser.java:569)
	at org.h2.engine.SessionLocal.prepareLocal(SessionLocal.java:631)
	at org.h2.engine.SessionLocal.prepareCommand(SessionLocal.java:554)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1116)
	at org.h2.jdbc.JdbcPreparedStatement.<init>(JdbcPreparedStatement.java:92)
	at org.h2.jdbc.JdbcConnection.prepareStatement(JdbcConnection.java:288)
	at g_contact.data.GroupDao.getAll(GroupDao.java:97)
	at g_contact.bll.GroupManager.getAll(GroupManager.java:26)
	at g_contact.ihm.View.showGroupData(View.java:92)
	at g_contact.ihm.Main.main(Main.java:204)
2023-05-30 01:17:59,385 ERROR [GroupDao] Error caused by :
org.h2.jdbc.JdbcSQLSyntaxErrorException: Column "contact_id" not found [42122-214]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:502)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:477)
	at org.h2.message.DbException.get(DbException.java:223)
	at org.h2.message.DbException.get(DbException.java:199)
	at org.h2.jdbc.JdbcResultSet.getColumnIndex(JdbcResultSet.java:3518)
	at org.h2.jdbc.JdbcResultSet.getInt(JdbcResultSet.java:337)
	at g_contact.data.GroupDao.resultToGroup(GroupDao.java:65)
	at g_contact.data.GroupDao.getAll(GroupDao.java:100)
	at g_contact.bll.GroupManager.getAll(GroupManager.java:26)
	at g_contact.ihm.View.showGroupData(View.java:92)
	at g_contact.ihm.Main.main(Main.java:204)
2023-05-30 01:19:57,629 ERROR [GroupDao] Error caused by :
org.h2.jdbc.JdbcSQLSyntaxErrorException: Column "contact_id" not found [42122-214]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:502)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:477)
	at org.h2.message.DbException.get(DbException.java:223)
	at org.h2.message.DbException.get(DbException.java:199)
	at org.h2.jdbc.JdbcResultSet.getColumnIndex(JdbcResultSet.java:3518)
	at org.h2.jdbc.JdbcResultSet.getInt(JdbcResultSet.java:337)
	at g_contact.data.GroupDao.resultToGroup(GroupDao.java:65)
	at g_contact.data.GroupDao.getAll(GroupDao.java:100)
	at g_contact.bll.GroupManager.getAll(GroupManager.java:26)
	at g_contact.ihm.View.showGroupData(View.java:92)
	at g_contact.ihm.Main.main(Main.java:204)
2023-05-30 01:31:37,989 ERROR [GroupDao] Error caused by :
org.h2.jdbc.JdbcSQLSyntaxErrorException: Column "contact_id" not found [42122-214]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:502)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:477)
	at org.h2.message.DbException.get(DbException.java:223)
	at org.h2.message.DbException.get(DbException.java:199)
	at org.h2.jdbc.JdbcResultSet.getColumnIndex(JdbcResultSet.java:3518)
	at org.h2.jdbc.JdbcResultSet.getInt(JdbcResultSet.java:337)
	at g_contact.data.GroupDao.resultToGroup(GroupDao.java:65)
	at g_contact.data.GroupDao.getAll(GroupDao.java:100)
	at g_contact.bll.GroupManager.getAll(GroupManager.java:26)
	at g_contact.ihm.View.showGroupData(View.java:92)
	at g_contact.ihm.Main.main(Main.java:214)
2023-05-30 02:41:30,676 ERROR [GroupDao] Error caused by :
org.h2.jdbc.JdbcSQLSyntaxErrorException: Column "contact_id" not found [42122-214]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:502)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:477)
	at org.h2.message.DbException.get(DbException.java:223)
	at org.h2.message.DbException.get(DbException.java:199)
	at org.h2.jdbc.JdbcResultSet.getColumnIndex(JdbcResultSet.java:3518)
	at org.h2.jdbc.JdbcResultSet.getInt(JdbcResultSet.java:337)
	at g_contact.data.GroupDao.resultToGroup(GroupDao.java:65)
	at g_contact.data.GroupDao.getAll(GroupDao.java:100)
	at g_contact.bll.GroupManager.getAll(GroupManager.java:26)
	at g_contact.ihm.View.showGroupData(View.java:92)
	at g_contact.ihm.Main.main(Main.java:204)
2023-05-30 02:43:56,118 ERROR [DbConnection] org.h2.jdbc.JdbcSQLNonTransientConnectionException: Database may be already in use: "C:/Users/dell/h2_Db/bibDb4.mv.db". Possible solutions: close all other connection(s); use the server mode [90020-214]
2023-05-30 02:44:11,575 ERROR [GroupDao] Error caused by :
org.h2.jdbc.JdbcSQLSyntaxErrorException: Column "contact_id" not found [42122-214]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:502)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:477)
	at org.h2.message.DbException.get(DbException.java:223)
	at org.h2.message.DbException.get(DbException.java:199)
	at org.h2.jdbc.JdbcResultSet.getColumnIndex(JdbcResultSet.java:3518)
	at org.h2.jdbc.JdbcResultSet.getInt(JdbcResultSet.java:337)
	at g_contact.data.GroupDao.resultToGroup(GroupDao.java:65)
	at g_contact.data.GroupDao.getAll(GroupDao.java:100)
	at g_contact.bll.GroupManager.getAll(GroupManager.java:26)
	at g_contact.ihm.View.showGroupData(View.java:92)
	at g_contact.ihm.Main.main(Main.java:204)
2023-05-30 02:46:45,640 ERROR [GroupDao] Error caused by :
org.h2.jdbc.JdbcSQLDataException: Invalid value "2" for parameter "columnIndex" [90008-214]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:646)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:477)
	at org.h2.message.DbException.get(DbException.java:223)
	at org.h2.message.DbException.getInvalidValueException(DbException.java:298)
	at org.h2.jdbc.JdbcResultSet.checkColumnIndex(JdbcResultSet.java:3524)
	at org.h2.jdbc.JdbcResultSet.getInt(JdbcResultSet.java:319)
	at g_contact.data.GroupDao.resultToGroup(GroupDao.java:65)
	at g_contact.data.GroupDao.getAll(GroupDao.java:100)
	at g_contact.bll.GroupManager.getAll(GroupManager.java:26)
	at g_contact.ihm.View.showGroupData(View.java:92)
	at g_contact.ihm.Main.main(Main.java:204)
2023-05-30 02:47:13,365 ERROR [GroupDao] Error caused by :
org.h2.jdbc.JdbcSQLDataException: Data conversion error converting "famille" [22018-214]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:506)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:477)
	at org.h2.message.DbException.get(DbException.java:212)
	at org.h2.value.ValueStringBase.getInt(ValueStringBase.java:133)
	at org.h2.jdbc.JdbcResultSet.getIntInternal(JdbcResultSet.java:348)
	at org.h2.jdbc.JdbcResultSet.getInt(JdbcResultSet.java:319)
	at g_contact.data.GroupDao.resultToGroup(GroupDao.java:65)
	at g_contact.data.GroupDao.getAll(GroupDao.java:100)
	at g_contact.bll.GroupManager.getAll(GroupManager.java:26)
	at g_contact.ihm.View.showGroupData(View.java:92)
	at g_contact.ihm.Main.main(Main.java:204)
Caused by: java.lang.NumberFormatException: For input string: "famille"
	at java.base/java.lang.NumberFormatException.forInputString(NumberFormatException.java:67)
	at java.base/java.lang.Integer.parseInt(Integer.java:665)
	at java.base/java.lang.Integer.parseInt(Integer.java:781)
	at org.h2.value.ValueStringBase.getInt(ValueStringBase.java:131)
	... 7 more
2023-05-30 03:01:44,787 ERROR [DbConnection] org.h2.jdbc.JdbcSQLNonTransientConnectionException: Database may be already in use: "C:/Users/dell/h2_Db/bibDb4.mv.db". Possible solutions: close all other connection(s); use the server mode [90020-214]
2023-05-30 03:02:01,335 ERROR [DbConnection] org.h2.jdbc.JdbcSQLNonTransientConnectionException: Database may be already in use: "C:/Users/dell/h2_Db/bibDb4.mv.db". Possible solutions: close all other connection(s); use the server mode [90020-214]
2023-05-30 03:02:15,763 ERROR [DbConnection] org.h2.jdbc.JdbcSQLNonTransientConnectionException: Database may be already in use: "C:/Users/dell/h2_Db/bibDb4.mv.db". Possible solutions: close all other connection(s); use the server mode [90020-214]
2023-05-30 03:02:40,063 ERROR [DbConnection] org.h2.jdbc.JdbcSQLNonTransientConnectionException: Database may be already in use: "C:/Users/dell/h2_Db/bibDb4.mv.db". Possible solutions: close all other connection(s); use the server mode [90020-214]
2023-05-30 03:03:08,072 ERROR [DbConnection] org.h2.jdbc.JdbcSQLNonTransientConnectionException: Database may be already in use: "C:/Users/dell/h2_Db/bibDb4.mv.db". Possible solutions: close all other connection(s); use the server mode [90020-214]
2023-05-30 03:03:19,606 ERROR [DbConnection] org.h2.jdbc.JdbcSQLNonTransientConnectionException: Database may be already in use: "C:/Users/dell/h2_Db/bibDb4.mv.db". Possible solutions: close all other connection(s); use the server mode [90020-214]
2023-05-30 03:04:36,347 ERROR [DbConnection] org.h2.jdbc.JdbcSQLNonTransientConnectionException: Database may be already in use: "C:/Users/dell/h2_Db/bibDb4.mv.db". Possible solutions: close all other connection(s); use the server mode [90020-214]
