2023-05-20 12:44:12,657 ERROR [ContactDao] Error cause by :
org.h2.jdbc.JdbcSQLIntegrityConstraintViolationException: Unique index or primary key violation: "PUBLIC.TELE1_UK_INDEX_6 ON PUBLIC.CONTACT(TELE1 NULLS FIRST) VALUES ( /* 15 */ '061206143311' )"; SQL statement:
insert into contact(nom,prenom,tele1,tele2,adresse,email_personnel,email_professionnel,genre)values(?,?,?,?,?,?,?,?) [23505-214]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:508)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:477)
	at org.h2.message.DbException.get(DbException.java:223)
	at org.h2.message.DbException.get(DbException.java:199)
	at org.h2.index.Index.getDuplicateKeyException(Index.java:525)
	at org.h2.mvstore.db.MVSecondaryIndex.checkUnique(MVSecondaryIndex.java:223)
	at org.h2.mvstore.db.MVSecondaryIndex.add(MVSecondaryIndex.java:184)
	at org.h2.mvstore.db.MVTable.addRow(MVTable.java:519)
	at org.h2.command.dml.Insert.insertRows(Insert.java:174)
	at org.h2.command.dml.Insert.update(Insert.java:135)
	at org.h2.command.dml.DataChangeStatement.update(DataChangeStatement.java:74)
	at org.h2.command.CommandContainer.update(CommandContainer.java:169)
	at org.h2.command.Command.executeUpdate(Command.java:252)
	at org.h2.jdbc.JdbcPreparedStatement.executeUpdateInternal(JdbcPreparedStatement.java:209)
	at org.h2.jdbc.JdbcPreparedStatement.executeUpdate(JdbcPreparedStatement.java:169)
	at g_contact.data.ContactDao.create(ContactDao.java:46)
	at g_contact.ihm.Main.main(Main.java:19)
2023-05-20 12:48:37,479 ERROR [ContactDao] Error cause by :
org.h2.jdbc.JdbcSQLIntegrityConstraintViolationException: Unique index or primary key violation: "PUBLIC.TELE1_UK_INDEX_6 ON PUBLIC.CONTACT(TELE1 NULLS FIRST) VALUES ( /* 15 */ '061206143311' )"; SQL statement:
insert into contact(nom,prenom,tele1,tele2,adresse,email_personnel,email_professionnel,genre)values(?,?,?,?,?,?,?,?) [23505-214]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:508)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:477)
	at org.h2.message.DbException.get(DbException.java:223)
	at org.h2.message.DbException.get(DbException.java:199)
	at org.h2.index.Index.getDuplicateKeyException(Index.java:525)
	at org.h2.mvstore.db.MVSecondaryIndex.checkUnique(MVSecondaryIndex.java:223)
	at org.h2.mvstore.db.MVSecondaryIndex.add(MVSecondaryIndex.java:184)
	at org.h2.mvstore.db.MVTable.addRow(MVTable.java:519)
	at org.h2.command.dml.Insert.insertRows(Insert.java:174)
	at org.h2.command.dml.Insert.update(Insert.java:135)
	at org.h2.command.dml.DataChangeStatement.update(DataChangeStatement.java:74)
	at org.h2.command.CommandContainer.update(CommandContainer.java:169)
	at org.h2.command.Command.executeUpdate(Command.java:252)
	at org.h2.jdbc.JdbcPreparedStatement.executeUpdateInternal(JdbcPreparedStatement.java:209)
	at org.h2.jdbc.JdbcPreparedStatement.executeUpdate(JdbcPreparedStatement.java:169)
	at g_contact.data.ContactDao.create(ContactDao.java:46)
	at g_contact.bll.ContactManager.addContact(ContactManager.java:28)
	at g_contact.ihm.Main.main(Main.java:22)
2023-05-20 12:53:43,458 ERROR [ContactDao] Error cause by :
org.h2.jdbc.JdbcSQLIntegrityConstraintViolationException: Unique index or primary key violation: "PUBLIC.TELE1_UK_INDEX_6 ON PUBLIC.CONTACT(TELE1 NULLS FIRST) VALUES ( /* 15 */ '061206143311' )"; SQL statement:
insert into contact(nom,prenom,tele1,tele2,adresse,email_personnel,email_professionnel,genre)values(?,?,?,?,?,?,?,?) [23505-214]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:508)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:477)
	at org.h2.message.DbException.get(DbException.java:223)
	at org.h2.message.DbException.get(DbException.java:199)
	at org.h2.index.Index.getDuplicateKeyException(Index.java:525)
	at org.h2.mvstore.db.MVSecondaryIndex.checkUnique(MVSecondaryIndex.java:223)
	at org.h2.mvstore.db.MVSecondaryIndex.add(MVSecondaryIndex.java:184)
	at org.h2.mvstore.db.MVTable.addRow(MVTable.java:519)
	at org.h2.command.dml.Insert.insertRows(Insert.java:174)
	at org.h2.command.dml.Insert.update(Insert.java:135)
	at org.h2.command.dml.DataChangeStatement.update(DataChangeStatement.java:74)
	at org.h2.command.CommandContainer.update(CommandContainer.java:169)
	at org.h2.command.Command.executeUpdate(Command.java:252)
	at org.h2.jdbc.JdbcPreparedStatement.executeUpdateInternal(JdbcPreparedStatement.java:209)
	at org.h2.jdbc.JdbcPreparedStatement.executeUpdate(JdbcPreparedStatement.java:169)
	at g_contact.data.ContactDao.create(ContactDao.java:46)
	at g_contact.bll.ContactManager.addContact(ContactManager.java:28)
	at g_contact.ihm.Main.main(Main.java:22)
2023-05-20 12:58:56,360 ERROR [ContactDao] Error caused by :
org.h2.jdbc.JdbcSQLIntegrityConstraintViolationException: Unique index or primary key violation: "PUBLIC.TELE1_UK_INDEX_6 ON PUBLIC.CONTACT(TELE1 NULLS FIRST) VALUES ( /* 15 */ '061206143311' )"; SQL statement:
insert into contact(nom,prenom,tele1,tele2,adresse,email_personnel,email_professionnel,genre)values(?,?,?,?,?,?,?,?) [23505-214]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:508)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:477)
	at org.h2.message.DbException.get(DbException.java:223)
	at org.h2.message.DbException.get(DbException.java:199)
	at org.h2.index.Index.getDuplicateKeyException(Index.java:525)
	at org.h2.mvstore.db.MVSecondaryIndex.checkUnique(MVSecondaryIndex.java:223)
	at org.h2.mvstore.db.MVSecondaryIndex.add(MVSecondaryIndex.java:184)
	at org.h2.mvstore.db.MVTable.addRow(MVTable.java:519)
	at org.h2.command.dml.Insert.insertRows(Insert.java:174)
	at org.h2.command.dml.Insert.update(Insert.java:135)
	at org.h2.command.dml.DataChangeStatement.update(DataChangeStatement.java:74)
	at org.h2.command.CommandContainer.update(CommandContainer.java:169)
	at org.h2.command.Command.executeUpdate(Command.java:252)
	at org.h2.jdbc.JdbcPreparedStatement.executeUpdateInternal(JdbcPreparedStatement.java:209)
	at org.h2.jdbc.JdbcPreparedStatement.executeUpdate(JdbcPreparedStatement.java:169)
	at g_contact.data.ContactDao.create(ContactDao.java:43)
	at g_contact.bll.ContactManager.addContact(ContactManager.java:28)
	at g_contact.ihm.Main.main(Main.java:22)
2023-05-20 13:03:20,659 ERROR [ContactDao] Error caused by :
org.h2.jdbc.JdbcSQLIntegrityConstraintViolationException: Unique index or primary key violation: "PUBLIC.TELE1_UK_INDEX_6 ON PUBLIC.CONTACT(TELE1 NULLS FIRST) VALUES ( /* 15 */ '061206143311' )"; SQL statement:
insert into contact(nom,prenom,tele1,tele2,adresse,email_personnel,email_professionnel,genre)values(?,?,?,?,?,?,?,?) [23505-214]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:508)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:477)
	at org.h2.message.DbException.get(DbException.java:223)
	at org.h2.message.DbException.get(DbException.java:199)
	at org.h2.index.Index.getDuplicateKeyException(Index.java:525)
	at org.h2.mvstore.db.MVSecondaryIndex.checkUnique(MVSecondaryIndex.java:223)
	at org.h2.mvstore.db.MVSecondaryIndex.add(MVSecondaryIndex.java:184)
	at org.h2.mvstore.db.MVTable.addRow(MVTable.java:519)
	at org.h2.command.dml.Insert.insertRows(Insert.java:174)
	at org.h2.command.dml.Insert.update(Insert.java:135)
	at org.h2.command.dml.DataChangeStatement.update(DataChangeStatement.java:74)
	at org.h2.command.CommandContainer.update(CommandContainer.java:169)
	at org.h2.command.Command.executeUpdate(Command.java:252)
	at org.h2.jdbc.JdbcPreparedStatement.executeUpdateInternal(JdbcPreparedStatement.java:209)
	at org.h2.jdbc.JdbcPreparedStatement.executeUpdate(JdbcPreparedStatement.java:169)
	at g_contact.data.ContactDao.create(ContactDao.java:43)
	at g_contact.bll.ContactManager.addContact(ContactManager.java:28)
	at g_contact.ihm.Main.main(Main.java:21)
2023-05-20 13:15:10,880 ERROR [ContactDao] Error caused by :
org.h2.jdbc.JdbcSQLSyntaxErrorException: Syntax error in SQL statement "SELECT * FROM Contact WHERE nom = ? and upper [*]prenom = ?"; SQL statement:
SELECT * FROM Contact WHERE nom = ? and upper prenom = ? [42000-214]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:502)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:477)
	at org.h2.message.DbException.get(DbException.java:223)
	at org.h2.message.DbException.get(DbException.java:199)
	at org.h2.message.DbException.getSyntaxError(DbException.java:247)
	at org.h2.command.Parser.getSyntaxError(Parser.java:898)
	at org.h2.command.Parser.prepareCommand(Parser.java:572)
	at org.h2.engine.SessionLocal.prepareLocal(SessionLocal.java:631)
	at org.h2.engine.SessionLocal.prepareCommand(SessionLocal.java:554)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1116)
	at org.h2.jdbc.JdbcPreparedStatement.<init>(JdbcPreparedStatement.java:92)
	at org.h2.jdbc.JdbcConnection.prepareStatement(JdbcConnection.java:288)
	at g_contact.data.ContactDao.findContactByName(ContactDao.java:131)
	at g_contact.bll.ContactManager.addContact(ContactManager.java:22)
	at g_contact.ihm.Main.main(Main.java:21)
2023-05-20 16:31:34,584 ERROR [DbConnection] org.h2.jdbc.JdbcSQLNonTransientConnectionException: Database may be already in use: "C:/Users/dell/h2_Db/bibDb4.mv.db". Possible solutions: close all other connection(s); use the server mode [90020-214]
2023-05-20 18:41:14,426 ERROR [DbConnection] org.h2.jdbc.JdbcSQLNonTransientConnectionException: Database may be already in use: "C:/Users/dell/h2_Db/bibDb4.mv.db". Possible solutions: close all other connection(s); use the server mode [90020-214]
2023-05-20 18:41:40,020 ERROR [DbConnection] org.h2.jdbc.JdbcSQLNonTransientConnectionException: Database may be already in use: "C:/Users/dell/h2_Db/bibDb4.mv.db". Possible solutions: close all other connection(s); use the server mode [90020-214]
2023-05-20 18:41:50,011 ERROR [DbConnection] org.h2.jdbc.JdbcSQLNonTransientConnectionException: Database may be already in use: "C:/Users/dell/h2_Db/bibDb4.mv.db". Possible solutions: close all other connection(s); use the server mode [90020-214]
2023-05-20 18:41:58,712 ERROR [DbConnection] org.h2.jdbc.JdbcSQLNonTransientConnectionException: Database may be already in use: "C:/Users/dell/h2_Db/bibDb4.mv.db". Possible solutions: close all other connection(s); use the server mode [90020-214]
2023-05-20 18:42:32,271 ERROR [DbConnection] org.h2.jdbc.JdbcSQLNonTransientConnectionException: Database may be already in use: "C:/Users/dell/h2_Db/bibDb4.mv.db". Possible solutions: close all other connection(s); use the server mode [90020-214]
2023-05-20 18:43:26,643 ERROR [DbConnection] org.h2.jdbc.JdbcSQLNonTransientConnectionException: Database may be already in use: "C:/Users/dell/h2_Db/bibDb4.mv.db". Possible solutions: close all other connection(s); use the server mode [90020-214]
2023-05-20 18:46:29,896 ERROR [DbConnection] org.h2.jdbc.JdbcSQLNonTransientConnectionException: Database may be already in use: "C:/Users/dell/h2_Db/bibDb4.mv.db". Possible solutions: close all other connection(s); use the server mode [90020-214]
2023-05-20 20:23:12,448 ERROR [ContactDao] Error caused by: 
org.h2.jdbc.JdbcSQLSyntaxErrorException: Column "EMAIL_PROFESSIONEL" not found; SQL statement:
UPDATE CONTACT SET nom=?,prenom=?,tele1=?,tele2=?,Adresse=?,email_personnel=?,email_professionel=?,genre=? WHERE id =? [42122-214]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:502)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:477)
	at org.h2.message.DbException.get(DbException.java:223)
	at org.h2.message.DbException.get(DbException.java:199)
	at org.h2.table.Table.getColumn(Table.java:749)
	at org.h2.command.Parser.readTableColumn(Parser.java:1084)
	at org.h2.command.Parser.readUpdateSetClause(Parser.java:1151)
	at org.h2.command.Parser.parseUpdate(Parser.java:1120)
	at org.h2.command.Parser.parsePrepared(Parser.java:858)
	at org.h2.command.Parser.parse(Parser.java:689)
	at org.h2.command.Parser.parse(Parser.java:661)
	at org.h2.command.Parser.prepareCommand(Parser.java:569)
	at org.h2.engine.SessionLocal.prepareLocal(SessionLocal.java:631)
	at org.h2.engine.SessionLocal.prepareCommand(SessionLocal.java:554)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1116)
	at org.h2.jdbc.JdbcPreparedStatement.<init>(JdbcPreparedStatement.java:92)
	at org.h2.jdbc.JdbcConnection.prepareStatement(JdbcConnection.java:288)
	at g_contact.data.ContactDao.update(ContactDao.java:107)
	at g_contact.bll.ContactManager.update(ContactManager.java:66)
	at g_contact.ihm.Main.main(Main.java:147)
2023-05-20 21:22:07,356 ERROR [ContactDao] Error caused by: 
org.h2.jdbc.JdbcSQLSyntaxErrorException: Column "EMAIL_PROFESSIONEL" not found; SQL statement:
UPDATE CONTACT SET nom=?,prenom=?,tele1=?,tele2=?,Adresse=?,email_personnel=?,email_professionel=?,genre=? WHERE nom =? and prenom =? [42122-214]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:502)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:477)
	at org.h2.message.DbException.get(DbException.java:223)
	at org.h2.message.DbException.get(DbException.java:199)
	at org.h2.table.Table.getColumn(Table.java:749)
	at org.h2.command.Parser.readTableColumn(Parser.java:1084)
	at org.h2.command.Parser.readUpdateSetClause(Parser.java:1151)
	at org.h2.command.Parser.parseUpdate(Parser.java:1120)
	at org.h2.command.Parser.parsePrepared(Parser.java:858)
	at org.h2.command.Parser.parse(Parser.java:689)
	at org.h2.command.Parser.parse(Parser.java:661)
	at org.h2.command.Parser.prepareCommand(Parser.java:569)
	at org.h2.engine.SessionLocal.prepareLocal(SessionLocal.java:631)
	at org.h2.engine.SessionLocal.prepareCommand(SessionLocal.java:554)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1116)
	at org.h2.jdbc.JdbcPreparedStatement.<init>(JdbcPreparedStatement.java:92)
	at org.h2.jdbc.JdbcConnection.prepareStatement(JdbcConnection.java:288)
	at g_contact.data.ContactDao.update(ContactDao.java:107)
	at g_contact.bll.ContactManager.update(ContactManager.java:66)
	at g_contact.ihm.Main.main(Main.java:134)
2023-05-20 21:45:13,477 ERROR [ContactDao] Error caused by: 
org.h2.jdbc.JdbcSQLSyntaxErrorException: Column "EMAIL_PROFESSIONEL" not found; SQL statement:
UPDATE CONTACT SET nom=?,prenom=?,tele1=?,tele2=?,Adresse=?,email_personnel=?,email_professionel=?,genre=? WHERE nom =? or prenom =? or tele1=? or tele2=? or Adresse=? or email_personnel=? or email_professionel=? or genre=? [42122-214]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:502)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:477)
	at org.h2.message.DbException.get(DbException.java:223)
	at org.h2.message.DbException.get(DbException.java:199)
	at org.h2.table.Table.getColumn(Table.java:749)
	at org.h2.command.Parser.readTableColumn(Parser.java:1084)
	at org.h2.command.Parser.readUpdateSetClause(Parser.java:1151)
	at org.h2.command.Parser.parseUpdate(Parser.java:1120)
	at org.h2.command.Parser.parsePrepared(Parser.java:858)
	at org.h2.command.Parser.parse(Parser.java:689)
	at org.h2.command.Parser.parse(Parser.java:661)
	at org.h2.command.Parser.prepareCommand(Parser.java:569)
	at org.h2.engine.SessionLocal.prepareLocal(SessionLocal.java:631)
	at org.h2.engine.SessionLocal.prepareCommand(SessionLocal.java:554)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1116)
	at org.h2.jdbc.JdbcPreparedStatement.<init>(JdbcPreparedStatement.java:92)
	at org.h2.jdbc.JdbcConnection.prepareStatement(JdbcConnection.java:288)
	at g_contact.data.ContactDao.update(ContactDao.java:106)
	at g_contact.bll.ContactManager.update(ContactManager.java:66)
	at g_contact.ihm.Main.main(Main.java:134)
2023-05-20 22:00:49,520 ERROR [DbConnection] org.h2.jdbc.JdbcSQLNonTransientConnectionException: Database may be already in use: "C:/Users/dell/h2_Db/bibDb4.mv.db". Possible solutions: close all other connection(s); use the server mode [90020-214]
2023-05-20 22:01:35,278 ERROR [ContactDao] Error caused by: 
org.h2.jdbc.JdbcSQLSyntaxErrorException: Column "EMAIL_PROFESSIONEL" not found; SQL statement:
UPDATE CONTACT SET nom=?,prenom='?',tele1='?',tele2='?',adresse='?',email_personnel='?',email_professionel='?',genre='?' WHERE nom ='?' or prenom ='?' or tele1='?' or tele2='?' or adresse='?' or email_personnel='?' or email_professionel='?' or genre='?' [42122-214]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:502)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:477)
	at org.h2.message.DbException.get(DbException.java:223)
	at org.h2.message.DbException.get(DbException.java:199)
	at org.h2.table.Table.getColumn(Table.java:749)
	at org.h2.command.Parser.readTableColumn(Parser.java:1084)
	at org.h2.command.Parser.readUpdateSetClause(Parser.java:1151)
	at org.h2.command.Parser.parseUpdate(Parser.java:1120)
	at org.h2.command.Parser.parsePrepared(Parser.java:858)
	at org.h2.command.Parser.parse(Parser.java:689)
	at org.h2.command.Parser.parse(Parser.java:661)
	at org.h2.command.Parser.prepareCommand(Parser.java:569)
	at org.h2.engine.SessionLocal.prepareLocal(SessionLocal.java:631)
	at org.h2.engine.SessionLocal.prepareCommand(SessionLocal.java:554)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1116)
	at org.h2.jdbc.JdbcPreparedStatement.<init>(JdbcPreparedStatement.java:92)
	at org.h2.jdbc.JdbcConnection.prepareStatement(JdbcConnection.java:288)
	at g_contact.data.ContactDao.update(ContactDao.java:107)
	at g_contact.bll.ContactManager.update(ContactManager.java:66)
	at g_contact.ihm.Main.main(Main.java:134)
2023-05-21 10:35:25,126 ERROR [ContactDao] Error caused by: 
org.h2.jdbc.JdbcSQLSyntaxErrorException: Column "EMAIL_PROFESSIONEL" not found; SQL statement:
UPDATE CONTACT SET nom=?,prenom='?',tele1='?',tele2='?',adresse='?',email_personnel='?',Email_professionnel='?',genre='?' WHERE nom ='?' or prenom ='?' or tele1='?' or tele2='?' or adresse='?' or email_personnel='?' or email_professionel='?' or genre='?' [42122-214]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:502)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:477)
	at org.h2.message.DbException.get(DbException.java:223)
	at org.h2.message.DbException.get(DbException.java:199)
	at org.h2.expression.ExpressionColumn.getColumnException(ExpressionColumn.java:244)
	at org.h2.expression.ExpressionColumn.optimizeOther(ExpressionColumn.java:226)
	at org.h2.expression.ExpressionColumn.optimize(ExpressionColumn.java:213)
	at org.h2.expression.condition.Comparison.optimize(Comparison.java:139)
	at org.h2.expression.condition.ConditionAndOrN.optimize(ConditionAndOrN.java:168)
	at org.h2.expression.Expression.optimizeCondition(Expression.java:148)
	at org.h2.command.dml.Update.doPrepare(Update.java:143)
	at org.h2.command.dml.DataChangeStatement.prepare(DataChangeStatement.java:37)
	at org.h2.command.Parser.prepareCommand(Parser.java:575)
	at org.h2.engine.SessionLocal.prepareLocal(SessionLocal.java:631)
	at org.h2.engine.SessionLocal.prepareCommand(SessionLocal.java:554)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1116)
	at org.h2.jdbc.JdbcPreparedStatement.<init>(JdbcPreparedStatement.java:92)
	at org.h2.jdbc.JdbcConnection.prepareStatement(JdbcConnection.java:288)
	at g_contact.data.ContactDao.update(ContactDao.java:107)
	at g_contact.bll.ContactManager.update(ContactManager.java:66)
	at g_contact.ihm.Main.main(Main.java:134)
2023-05-21 10:36:52,416 ERROR [DbConnection] org.h2.jdbc.JdbcSQLNonTransientConnectionException: Database may be already in use: "C:/Users/dell/h2_Db/bibDb4.mv.db". Possible solutions: close all other connection(s); use the server mode [90020-214]
2023-05-21 10:38:31,612 ERROR [ContactDao] Error caused by: 
org.h2.jdbc.JdbcSQLSyntaxErrorException: Column "EMAIL_PROFESSIONEL" not found; SQL statement:
UPDATE CONTACT SET nom=?,prenom='?',tele1='?',tele2='?',adresse='?',email_personnel='?',Email_professionnel='?',genre='?' WHERE nom ='?' or prenom ='?' or tele1='?' or tele2='?' or adresse='?' or email_personnel='?' or email_professionel='?' or genre='?' [42122-214]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:502)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:477)
	at org.h2.message.DbException.get(DbException.java:223)
	at org.h2.message.DbException.get(DbException.java:199)
	at org.h2.expression.ExpressionColumn.getColumnException(ExpressionColumn.java:244)
	at org.h2.expression.ExpressionColumn.optimizeOther(ExpressionColumn.java:226)
	at org.h2.expression.ExpressionColumn.optimize(ExpressionColumn.java:213)
	at org.h2.expression.condition.Comparison.optimize(Comparison.java:139)
	at org.h2.expression.condition.ConditionAndOrN.optimize(ConditionAndOrN.java:168)
	at org.h2.expression.Expression.optimizeCondition(Expression.java:148)
	at org.h2.command.dml.Update.doPrepare(Update.java:143)
	at org.h2.command.dml.DataChangeStatement.prepare(DataChangeStatement.java:37)
	at org.h2.command.Parser.prepareCommand(Parser.java:575)
	at org.h2.engine.SessionLocal.prepareLocal(SessionLocal.java:631)
	at org.h2.engine.SessionLocal.prepareCommand(SessionLocal.java:554)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1116)
	at org.h2.jdbc.JdbcPreparedStatement.<init>(JdbcPreparedStatement.java:92)
	at org.h2.jdbc.JdbcConnection.prepareStatement(JdbcConnection.java:288)
	at g_contact.data.ContactDao.update(ContactDao.java:107)
	at g_contact.bll.ContactManager.update(ContactManager.java:66)
	at g_contact.ihm.Main.main(Main.java:134)
2023-05-21 10:39:57,187 ERROR [ContactDao] Error caused by: 
org.h2.jdbc.JdbcSQLDataException: Invalid value "2" for parameter "parameterIndex" [90008-214]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:646)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:477)
	at org.h2.message.DbException.get(DbException.java:223)
	at org.h2.message.DbException.getInvalidValueException(DbException.java:298)
	at org.h2.jdbc.JdbcPreparedStatement.setParameter(JdbcPreparedStatement.java:1395)
	at org.h2.jdbc.JdbcPreparedStatement.setString(JdbcPreparedStatement.java:378)
	at g_contact.data.ContactDao.update(ContactDao.java:109)
	at g_contact.bll.ContactManager.update(ContactManager.java:66)
	at g_contact.ihm.Main.main(Main.java:134)
2023-05-21 10:47:13,064 ERROR [ContactDao] Error caused by: 
org.h2.jdbc.JdbcSQLDataException: Invalid value "10" for parameter "parameterIndex" [90008-214]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:646)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:477)
	at org.h2.message.DbException.get(DbException.java:223)
	at org.h2.message.DbException.getInvalidValueException(DbException.java:298)
	at org.h2.jdbc.JdbcPreparedStatement.setParameter(JdbcPreparedStatement.java:1395)
	at org.h2.jdbc.JdbcPreparedStatement.setString(JdbcPreparedStatement.java:378)
	at g_contact.data.ContactDao.update(ContactDao.java:117)
	at g_contact.bll.ContactManager.update(ContactManager.java:66)
	at g_contact.ihm.Main.main(Main.java:134)
2023-05-21 10:49:07,249 ERROR [ContactDao] Error caused by: 
org.h2.jdbc.JdbcSQLDataException: Invalid value "10" for parameter "parameterIndex" [90008-214]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:646)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:477)
	at org.h2.message.DbException.get(DbException.java:223)
	at org.h2.message.DbException.getInvalidValueException(DbException.java:298)
	at org.h2.jdbc.JdbcPreparedStatement.setParameter(JdbcPreparedStatement.java:1395)
	at org.h2.jdbc.JdbcPreparedStatement.setString(JdbcPreparedStatement.java:378)
	at g_contact.data.ContactDao.update(ContactDao.java:117)
	at g_contact.bll.ContactManager.update(ContactManager.java:66)
	at g_contact.ihm.Main.main(Main.java:134)
